server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luzacao/aispringcloud.git
          searchPaths: config
          username: luzacao
          password: lu13983223314
          label: master


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/